version : '2.1'

services:
  db: 
    image: postgres:9.6.1
    volumes:
      - ./postgresSQL/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=boarddb
      - POSTGRES_USER=boarduser
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"